load("@platformio_rules//platformio:platformio.bzl", "platformio_project", "platformio_library")
load("@nanobind_bazel//:build_defs.bzl", "nanobind_extension")

platformio_project(
    name = "rover_control",
    src = "rover_control.cc",
    board = "teensy41",
    framework = "arduino",
    platform = "teensy",
)

cc_library(
    name = "dynamics",
    hdrs = ["dynamics.h"],
    deps = [":linalg"]
)

cc_library(
    name = "linalg",
    hdrs = ["linalg.h"],
)

cc_library(
    name = "quaternion",
    hdrs = ["quaternion.h"],
    deps = [":linalg"],
)

cc_library(
    name = "cfd_lib",
    hdrs = ["cfd_lib.h", "cfd_lib_impl.h"],
    deps = [":linalg"]
)

cc_binary(
    name = "cfd",
    srcs = ["cfd.cc"],
    deps = [":stl_reader", ":cfd_lib", ":linalg"]
)

cc_library(
    name = "stl_reader",
    hdrs = ["stl_reader.h"]
)

cc_library(
    name = "controller",
    hdrs = ["controller.h"],
    srcs = ["controller.cc"],
    deps = [":linalg"]
)

nanobind_extension(
    name = "dynamics_py",
    srcs = ["dynamics_py.cc"],
    deps = [
        ":dynamics"
    ]
)

py_binary(
    name = "dynamics_test",
    srcs = ["dynamics_test.py"],
    main = "dynamics_test.py",
    data = [":dynamics_py"]
)