load("@nanobind_bazel//:build_defs.bzl", "nanobind_extension")

cc_library(
    name = "dynamics",
    hdrs = ["dynamics.h"],
    deps = [":linalg", ":controller"]
)

cc_library(
    name = "linalg",
    hdrs = ["linalg.h"],
)

cc_library(
    name = "quaternion",
    hdrs = ["quaternion.h"],
    deps = [":linalg"],
)

cc_library(
    name = "cfd_lib",
    hdrs = ["cfd_lib.h", "cfd_lib_impl.h"],
    deps = [":linalg"]
)

cc_binary(
    name = "cfd",
    srcs = ["cfd.cc"],
    deps = [":stl_reader", ":cfd_lib", ":linalg"]
)

cc_library(
    name = "stl_reader",
    hdrs = ["stl_reader.h"]
)

cc_library(
    name = "controller",
    hdrs = ["controller.h"],
    srcs = ["controller.cc"],
    deps = [":linalg", ":quaternion"]
)

nanobind_extension(
    name = "dynamics_py",
    srcs = ["dynamics_py.cc"],
    deps = [
        ":dynamics"
    ]
)

py_binary(
    name = "dynamics_test",
    srcs = ["dynamics_test.py"],
    main = "dynamics_test.py",
    data = [":dynamics_py"],
    deps = [
        "@pip//matplotlib",
        "@pip//numpy",
        "@pip//vedo",
    ]
)

genrule(
    name = "format_cpp",
    srcs = glob(["**/*.cc", "**/*.h"]),
    outs = ["_format_cpp_done"],
    cmd = "clang-format -i $(SRCS) && touch $@",
)

genrule(
    name = "format_py",
    srcs = glob(["**/*.py"]),
    outs = ["_format_py_done"],
    cmd = "black $(SRCS) && touch $@",
)